import Foundation

/// One folder, two format subtrees, and Quail is the only thing that
/// writes to it (docs/ARCHITECTURE.md §6). Every runtime is always given
/// one of this store's explicit subdirectories rather than relying on its
/// own default location, per AGENTS.md.
///
/// ```
/// <rootURL>/
///   gguf/            llama.cpp models — router-mode --models-dir
///   mlx/              MLX safetensors folders — oMLX/Rapid-MLX (Phase 3)
///   hf-cache/         HF_HOME for any runtime-initiated download
///   .partial/         in-progress HFDownloader downloads — see HFDownloader.swift
///   presets.ini       generated by regeneratePresets(catalog:), below
///   catalog.json      this store's installed-models index — see StoreCatalog.swift
/// ```
struct ModelStore: Sendable, Equatable {
    let rootURL: URL

    init(rootURL: URL = Paths.defaultModelsDirectory) {
        self.rootURL = rootURL
    }

    var ggufDirectory: URL {
        rootURL.appendingPathComponent("gguf", isDirectory: true)
    }

    var mlxDirectory: URL {
        rootURL.appendingPathComponent("mlx", isDirectory: true)
    }

    var hfCacheDirectory: URL {
        rootURL.appendingPathComponent("hf-cache", isDirectory: true)
    }

    /// Where `HFDownloader.install` keeps in-progress downloads — one
    /// subdirectory per repo (`/` sanitized to `--`), each holding a
    /// `.partial` file and a JSON sidecar per file still downloading or
    /// awaiting verification. Left in place on cancel or app quit; that's
    /// the resume state for next time.
    var partialDirectory: URL {
        rootURL.appendingPathComponent(".partial", isDirectory: true)
    }

    var presetsFile: URL {
        rootURL.appendingPathComponent("presets.ini", isDirectory: false)
    }

    var catalogFile: URL {
        rootURL.appendingPathComponent("catalog.json", isDirectory: false)
    }

    /// Creates every directory this store points at, if missing. Safe to
    /// call repeatedly — `AppState.start()` does, on every Start.
    func ensureDirectoriesExist() throws {
        let fm = FileManager.default
        for url in [rootURL, ggufDirectory, mlxDirectory, hfCacheDirectory, partialDirectory] {
            try fm.createDirectory(at: url, withIntermediateDirectories: true)
        }
    }

    // MARK: - Catalog

    /// Reads `catalog.json`, defaulting to empty if it's missing,
    /// unreadable, or malformed — a corrupt catalog should never stop
    /// Quail from starting the server.
    func loadCatalog() -> StoreCatalog {
        guard let data = try? Data(contentsOf: catalogFile) else { return StoreCatalog() }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return (try? decoder.decode(StoreCatalog.self, from: data)) ?? StoreCatalog()
    }

    /// Writes `catalog.json` atomically, creating the store's directories
    /// first if needed.
    func saveCatalog(_ catalog: StoreCatalog) throws {
        try ensureDirectoriesExist()
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(catalog)
        try data.write(to: catalogFile, options: .atomic)
    }

    // MARK: - GGUF files actually on disk

    /// Every `.gguf` file directly inside `gguf/`, excluding vision
    /// projector companions (`mmproj-*`, per docs/ARCHITECTURE.md §6's
    /// "paired by name" note) — those are attached to their model's preset
    /// section via `mmproj =` (see `regeneratePresets`), not given one of
    /// their own — and excluding every shard but the first of a
    /// multi-file split model (`...-00002-of-00007.gguf`), which
    /// llama.cpp loads implicitly by following the split manifest from
    /// `...-00001-of-...`; a preset per later shard would have the router
    /// try to load fragments standalone. Sorted by filename for a stable,
    /// predictable `presets.ini`.
    func installedGGUFFiles() -> [URL] {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(at: ggufDirectory, includingPropertiesForKeys: nil) else {
            return []
        }
        return files
            .filter { $0.pathExtension.lowercased() == "gguf" }
            .filter { !$0.lastPathComponent.hasPrefix("mmproj-") }
            .filter { (Self.shardIndex(of: $0) ?? 1) == 1 }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    /// The 1-based shard number in a `name-00002-of-00007.gguf` stem, or
    /// `nil` for an ordinary single-file name. Matches the exact
    /// five-digit llama.cpp convention rather than any-digits, so a real
    /// model named e.g. `Llama-3-8B` never trips it.
    private static func shardIndex(of url: URL) -> Int? {
        let stem = url.deletingPathExtension().lastPathComponent
        guard let ofRange = stem.range(of: "-of-") else { return nil }
        let before = stem[..<ofRange.lowerBound]
        let after = stem[ofRange.upperBound...]
        guard !after.isEmpty, after.allSatisfy(\.isNumber), after.count == 5,
              let dash = before.lastIndex(of: "-")
        else { return nil }
        let digits = before[before.index(after: dash)...]
        guard digits.count == 5, digits.allSatisfy(\.isNumber) else { return nil }
        return Int(digits)
    }

    // MARK: - Catalog refresh from disk

    /// The store's catalog, reconciled against what's actually on disk —
    /// the same "disk is the source of truth, catalog is the index"
    /// stance as `regeneratePresets` (ADR D-012): files no longer on disk
    /// lose their rows (ARCHITECTURE.md §6: "Deletion removes the files
    /// and the catalog row"), files on disk without a row gain one (a
    /// hand-placed model), and every surviving row's `bytes` and
    /// `contextSize` are recomputed. Download-specific fields
    /// (`sourceRepo`, `sha256`, `quant`, `family`) are kept as-is since
    /// the disk can't re-derive them.
    ///
    /// `contextSize` is Phase 2 step 4's deferred wiring: each model's
    /// GGUF/MLX metadata is parsed (cheaply — `GGUFMetadata` memory-maps),
    /// fed to `FitEstimator` against `device` under `ggufRuntime` (MLX
    /// directories always evaluate under `.omlx` — that's the only
    /// format-aware choice for them), and the resulting
    /// resulting `FitEstimator.automaticContextSize` is stored as the
    /// row's `contextSize` (ADR D-020) — what `presets.ini` uses unless the
    /// user picked a size (`userContextSize`, never touched here).
    func refreshedCatalog(
        device: DeviceInfo,
        ggufRuntime: RuntimeID,
        bandwidthTable _: [String: Double],
        now: Date = .init()
    ) -> StoreCatalog {
        var result = loadCatalog()
        var remaining: Set<String> = Set(result.entries.map(\.id))

        for file in installedGGUFFiles() {
            let id = file.deletingPathExtension().lastPathComponent
            let bytes = fileSize(of: file)
            let shape = (try? GGUFMetadata.read(from: file)).flatMap { ModelShape.from(gguf: $0, weightBytes: bytes) }
            let contextSize = shape.flatMap {
                FitEstimator.automaticContextSize(model: $0, device: device, runtime: ggufRuntime)
            }
            if let index = result.entries.firstIndex(where: { $0.id == id }) {
                result.entries[index].bytes = bytes
                result.entries[index].contextSize = contextSize
                result.entries[index].trainedContext = shape?.trainedContext
                remaining.remove(id)
            } else {
                result.entries.append(
                    InstalledModel(
                        id: id, format: .gguf, bytes: bytes, contextSize: contextSize,
                        trainedContext: shape?.trainedContext, addedAt: now
                    )
                )
            }
        }

        for directory in installedMLXDirectories() {
            let id = directory.lastPathComponent
            let bytes = directorySize(of: directory)
            let contextSize = (try? MLXMetadata.read(from: directory.appendingPathComponent("config.json")))
                .flatMap { ModelShape.from(mlx: $0, weightBytes: bytes) }
                .flatMap { FitEstimator.automaticContextSize(model: $0, device: device, runtime: .omlx) }
            if let index = result.entries.firstIndex(where: { $0.id == id }) {
                result.entries[index].bytes = bytes
                result.entries[index].contextSize = contextSize
                remaining.remove(id)
            } else {
                result.entries.append(
                    InstalledModel(
                        id: id,
                        format: .mlxSafetensors,
                        bytes: bytes,
                        contextSize: contextSize,
                        addedAt: now
                    )
                )
            }
        }

        result.entries.removeAll { remaining.contains($0.id) }
        result.entries.sort { $0.id < $1.id }
        return result
    }

    /// Every MLX model directory inside `mlx/` — a subdirectory that
    /// contains a `config.json`, ARCHITECTURE.md §6's layout. A stray
    /// folder without one isn't a model and gets no row/presence
    /// guarantee; the `.partial` staging directory never lives here, so
    /// there's no filtering hazard like the GGUF `mmproj-` exclusion.
    func installedMLXDirectories() -> [URL] {
        let fm = FileManager.default
        guard let entries = try? fm
            .contentsOfDirectory(at: mlxDirectory, includingPropertiesForKeys: [.isDirectoryKey])
        else {
            return []
        }
        return entries
            .filter { fm.fileExists(atPath: $0.appendingPathComponent("config.json").path) }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    /// Sum of all file sizes directly inside a directory plus one level
    /// down — real MLX repos keep everything flat, and the one repo shape
    /// with nested content (`snapshots/` from an HF cache) never lands in
    /// this store, since Quail is the only thing that writes here.
    func directorySize(of directory: URL) -> Int64 {
        let fm = FileManager.default
        guard let walker = fm.enumerator(
            at: directory,
            includingPropertiesForKeys: [.totalFileAllocatedSizeKey, .fileSizeKey]
        ) else {
            return 0
        }
        var total: Int64 = 0
        for case let url as URL in walker {
            let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
            if values?.isRegularFile == true {
                total += Int64(values?.fileSize ?? 0)
            }
        }
        return total
    }

    func fileSize(of url: URL) -> Int64 {
        let values = try? url.resourceValues(forKeys: [.fileSizeKey])
        return Int64(values?.fileSize ?? 0)
    }

    // MARK: - presets.ini

    /// Regenerates `presets.ini` from whatever `.gguf` files are actually
    /// on disk right now — not from `catalog`'s entries — so a model
    /// dropped in by hand (docs/IMPLEMENTATION_PLAN.md Phase 1's "Done
    /// when": "placing a GGUF ... and clicking Start") gets a preset too,
    /// not just ones Quail downloaded itself. `catalog` is still consulted
    /// per file for a `contextSize` override; `defaultContextSize` (see
    /// docs/ARCHITECTURE.md §7: "Default C is 8,192") is used for anything
    /// without a catalog entry, or without one that includes a
    /// `contextSize` yet — which today is everything, since Phase 2 step
    /// 4's `FitEstimator` is what actually sets one.
    ///
    /// Sampling defaults (temperature, top-p, ...) are deliberately not
    /// written here: llama-server already has its own, and Quail has no
    /// Settings surface yet to let anyone override them. Writing arbitrary
    /// chosen numbers with no UI behind them would be guessing, not a
    /// decision.
    ///
    /// - Parameter defaultModelID: `Config.defaultModelID` (ADR D-017) —
    ///   that one section, if it's still actually installed, gets
    ///   `load-on-startup = true`, confirmed against the real vendored
    ///   binary to make router mode load it immediately at startup with
    ///   no client request needed. `nil`/not-installed writes no such
    ///   key anywhere, today's behaviour (every preset stays unloaded
    ///   until a Load click or a request names it).
    /// `mmproj-<modelID>.gguf`: the name Quail saves a model's vision
    /// projector under. Repos all ship theirs as `mmproj-F16.gguf` (or
    /// BF16/F32), which can't live side by side in one flat folder.
    static func projectorFilename(forModelID id: String) -> String {
        "mmproj-\(id).gguf"
    }

    func regeneratePresets(
        catalog: StoreCatalog,
        defaultContextSize: Int = 8192,
        defaultModelID: String? = nil
    ) throws {
        try ensureDirectoriesExist()
        var ini = ""
        for file in installedGGUFFiles() {
            let alias = file.deletingPathExtension().lastPathComponent
            let contextSize = catalog.entries.first { $0.id == alias }?.effectiveContextSize ?? defaultContextSize
            ini += "[\(alias)]\n"
            ini += "model = \(file.path)\n"
            // llama-server's --models-preset parser keys presets by the
            // CLI flag's own name (dashes, not underscores) — confirmed by
            // testing it: n_gpu_layers made the router fail to start with
            // "option 'n_gpu_layers' not recognized in preset ...",
            // n-gpu-layers (matching --n-gpu-layers) doesn't.
            ini += "n-gpu-layers = 99\n"
            ini += "ctx-size = \(contextSize)\n"
            // A vision model's projector: without this the router loads
            // the model text-only, even though the projector was
            // downloaded next to it (found by review — nothing wrote it).
            let projector = ggufDirectory.appendingPathComponent(Self.projectorFilename(forModelID: alias))
            if FileManager.default.fileExists(atPath: projector.path) {
                ini += "mmproj = \(projector.path)\n"
            }
            if alias == defaultModelID {
                ini += "load-on-startup = true\n"
            }
            ini += "\n"
        }
        try ini.write(to: presetsFile, atomically: true, encoding: .utf8)
    }
}
