import Foundation

/// One folder, two format subtrees, and Quail is the only thing that
/// writes to it (docs/ARCHITECTURE.md §6). Every runtime is always given
/// one of this store's explicit subdirectories rather than relying on its
/// own default location, per AGENTS.md.
///
/// ```
/// <rootURL>/
///   gguf/            llama.cpp models — router-mode --models-dir
///   mlx/              MLX safetensors folders — oMLX/Rapid-MLX (Phase 3)
///   hf-cache/         HF_HOME for any runtime-initiated download
///   presets.ini       generated by regeneratePresets(catalog:), below
///   catalog.json      this store's installed-models index — see StoreCatalog.swift
/// ```
struct ModelStore: Sendable, Equatable {
    let rootURL: URL

    init(rootURL: URL = Paths.defaultModelsDirectory) {
        self.rootURL = rootURL
    }

    var ggufDirectory: URL {
        rootURL.appendingPathComponent("gguf", isDirectory: true)
    }

    var mlxDirectory: URL {
        rootURL.appendingPathComponent("mlx", isDirectory: true)
    }

    var hfCacheDirectory: URL {
        rootURL.appendingPathComponent("hf-cache", isDirectory: true)
    }

    var presetsFile: URL {
        rootURL.appendingPathComponent("presets.ini", isDirectory: false)
    }

    var catalogFile: URL {
        rootURL.appendingPathComponent("catalog.json", isDirectory: false)
    }

    /// Creates every directory this store points at, if missing. Safe to
    /// call repeatedly — `AppState.start()` does, on every Start.
    func ensureDirectoriesExist() throws {
        let fm = FileManager.default
        for url in [rootURL, ggufDirectory, mlxDirectory, hfCacheDirectory] {
            try fm.createDirectory(at: url, withIntermediateDirectories: true)
        }
    }

    // MARK: - Catalog

    /// Reads `catalog.json`, defaulting to empty if it's missing,
    /// unreadable, or malformed — a corrupt catalog should never stop
    /// Quail from starting the server.
    func loadCatalog() -> StoreCatalog {
        guard let data = try? Data(contentsOf: catalogFile) else { return StoreCatalog() }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return (try? decoder.decode(StoreCatalog.self, from: data)) ?? StoreCatalog()
    }

    /// Writes `catalog.json` atomically, creating the store's directories
    /// first if needed.
    func saveCatalog(_ catalog: StoreCatalog) throws {
        try ensureDirectoriesExist()
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(catalog)
        try data.write(to: catalogFile, options: .atomic)
    }

    // MARK: - GGUF files actually on disk

    /// Every `.gguf` file directly inside `gguf/`, excluding vision
    /// projector companions (`mmproj-*`, per docs/ARCHITECTURE.md §6's
    /// "paired by name" note) — those load implicitly alongside their
    /// matching main model and don't get their own preset section or
    /// router-mode entry. Sorted by filename for a stable, predictable
    /// `presets.ini`.
    func installedGGUFFiles() -> [URL] {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(at: ggufDirectory, includingPropertiesForKeys: nil) else {
            return []
        }
        return files
            .filter { $0.pathExtension.lowercased() == "gguf" }
            .filter { !$0.lastPathComponent.hasPrefix("mmproj-") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    // MARK: - presets.ini

    /// Regenerates `presets.ini` from whatever `.gguf` files are actually
    /// on disk right now — not from `catalog`'s entries — so a model
    /// dropped in by hand (docs/IMPLEMENTATION_PLAN.md Phase 1's "Done
    /// when": "placing a GGUF ... and clicking Start") gets a preset too,
    /// not just ones Quail downloaded itself. `catalog` is still consulted
    /// per file for a `contextSize` override; `defaultContextSize` (see
    /// docs/ARCHITECTURE.md §7: "Default C is 8,192") is used for anything
    /// without a catalog entry, or without one that includes a
    /// `contextSize` yet — which today is everything, since Phase 2 step
    /// 4's `FitEstimator` is what actually sets one.
    ///
    /// Sampling defaults (temperature, top-p, ...) are deliberately not
    /// written here: llama-server already has its own, and Quail has no
    /// Settings surface yet to let anyone override them. Writing arbitrary
    /// chosen numbers with no UI behind them would be guessing, not a
    /// decision.
    func regeneratePresets(catalog: StoreCatalog, defaultContextSize: Int = 8192) throws {
        try ensureDirectoriesExist()
        var ini = ""
        for file in installedGGUFFiles() {
            let alias = file.deletingPathExtension().lastPathComponent
            let contextSize = catalog.entries.first { $0.id == alias }?.contextSize ?? defaultContextSize
            ini += "[\(alias)]\n"
            ini += "model = \(file.path)\n"
            // llama-server's --models-preset parser keys presets by the
            // CLI flag's own name (dashes, not underscores) — confirmed by
            // testing it: n_gpu_layers made the router fail to start with
            // "option 'n_gpu_layers' not recognized in preset ...",
            // n-gpu-layers (matching --n-gpu-layers) doesn't.
            ini += "n-gpu-layers = 99\n"
            ini += "ctx-size = \(contextSize)\n"
            ini += "\n"
        }
        try ini.write(to: presetsFile, atomically: true, encoding: .utf8)
    }
}
