import Foundation

/// The MLX models Rapid-MLX's own catalog lists that Quail server can run, and its per-Mac picks (ADR D-058):
/// `Resources/mlx-models.json`, generated by `scripts/import-rapid-mlx` from Rapid-MLX's bundled data files
/// (Apache-2.0), and refreshed weekly like the curated catalog. It widens the Add Model list's MLX choices beyond
/// the hand-curated families without anyone curating them by hand.
struct RapidMLXCatalog: Sendable, Equatable, Codable {
    struct Source: Sendable, Equatable, Codable {
        var name: String
        var version: String
        var license: String
        var url: String
    }

    struct Model: Sendable, Hashable, Codable {
        var alias: String
        var repo: String
        var modelType: String
        var sizeBytes: Int64?
        var moe: Bool
        /// Reads images in Quail (an architecture `MLXVision` loads).
        var vision: Bool
        var reasoning: Bool
        var minMemoryGB: Int?
    }

    struct Pick: Sendable, Equatable, Codable {
        /// "smart" (the most capable that fits) or "fast".
        var role: String
        var alias: String
        var repo: String
        var footprintGB: Double
        /// As Rapid-MLX measured it on its own reference Mac.
        var tokensPerSecond: Double
        var limitations: [String]
    }

    struct Tier: Sendable, Equatable, Codable {
        var minimumMemoryGB: Int
        var picks: [Pick]
    }

    static let schemaVersion = 1

    var schemaVersion: Int
    var revision: Int
    var asOf: String?
    var source: Source
    var models: [Model]
    var recommendations: [Tier]

    /// The picks for a Mac with `bytes` of memory: the largest tier it reaches.
    func picks(forMemoryBytes bytes: Int64) -> [Pick] {
        let gigabytes = Int(bytes / 1_073_741_824)
        return recommendations
            .filter { $0.minimumMemoryGB <= gigabytes }
            .max { $0.minimumMemoryGB < $1.minimumMemoryGB }?.picks ?? []
    }

    /// Each model as a row of the Add Model list, after the curated families.
    var families: [Catalog.Family] {
        models.map { model in
            let name = String(model.repo.split(separator: "/").last ?? Substring(model.repo))
            var strengths = ["chat"]
            if model.reasoning {
                strengths.append("reasoning")
            }
            if model.vision {
                strengths.append("vision")
            }
            return Catalog.Family(
                id: model.repo,
                name: name,
                paramsB: Self.parameters(in: model.alias),
                activeParamsB: model.moe ? Self.activeParameters(in: model.alias) : nil,
                role: "general",
                strengths: strengths,
                mlx: Catalog.MLXVariant(repo: model.repo, vision: model.vision),
                isCurated: false,
                rapidMLX: model
            )
        }
    }

    /// Billions of parameters from an alias like "qwen3.6-35b-a3b-4bit" (35) or "gemma-4-e4b-4bit" (4);
    /// nil when it doesn't say.
    static func parameters(in alias: String) -> Double? {
        number(in: alias, pattern: #"(?:^|[-_])e?(\d+(?:\.\d+)?)b(?=$|[-_])"#)
    }

    /// Active billions for a mixture of experts: the "a3b" in "qwen3.6-35b-a3b-4bit".
    static func activeParameters(in alias: String) -> Double? {
        number(in: alias, pattern: #"(?:^|[-_])a(\d+(?:\.\d+)?)b(?=$|[-_])"#)
    }

    private static func number(in text: String, pattern: String) -> Double? {
        guard let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]),
              let match = regex.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)),
              let range = Range(match.range(at: 1), in: text)
        else { return nil }
        return Double(text[range])
    }

    // MARK: - Loading

    static func bundled(in bundle: Bundle = .main) -> RapidMLXCatalog? {
        guard let url = bundle.url(forResource: "mlx-models", withExtension: "json"),
              let data = try? Data(contentsOf: url)
        else { return nil }
        return decode(data)
    }

    /// The document, if it's the schema this build reads.
    static func decode(_ data: Data) -> RapidMLXCatalog? {
        guard let catalog = try? JSONDecoder().decode(RapidMLXCatalog.self, from: data),
              catalog.schemaVersion == schemaVersion
        else { return nil }
        return catalog
    }

    /// The bundled copy, or the refreshed one when its revision is at least as new.
    static func current(locations: Catalog.Locations) -> RapidMLXCatalog? {
        let bundled = bundled(in: locations.bundle)
        guard let cached = loadRefreshCache(from: locations.rapidMLXRefreshFile)?.catalog,
              cached.revision >= bundled?.revision ?? 0
        else { return bundled }
        return cached
    }

    /// The weekly refresh's envelope, as `Catalog.CachedRefresh` is for the curated catalog.
    struct CachedRefresh: Sendable, Equatable, Codable {
        var fetchedAt: Date
        var catalog: RapidMLXCatalog
    }

    static func loadRefreshCache(from url: URL) -> CachedRefresh? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let cached = try? decoder.decode(CachedRefresh.self, from: data),
              cached.catalog.schemaVersion == schemaVersion
        else { return nil }
        return cached
    }

    static func saveRefreshCache(_ catalog: RapidMLXCatalog, fetchedAt: Date, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.sortedKeys]
        try encoder.encode(CachedRefresh(fetchedAt: fetchedAt, catalog: catalog)).write(to: url, options: .atomic)
    }
}
