#!/usr/bin/env python3
"""Builds Quail/Resources/THIRD_PARTY_NOTICES.md (ADR D-044).

    python3 Config/generate-notices.py            write the file
    python3 Config/generate-notices.py --check    fail if the committed file is out of date

Versions come from Package.resolved, licence texts from the package checkouts Xcode leaves in
DerivedData/SourcePackages (so run it after a build) and from Vendor/. Config/third-party.json says
which packages Quail knows about; one that isn't listed, or a listed one that's gone, is an error.
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESOLVED = ROOT / "Quail.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
OUTPUT = ROOT / "Quail/Resources/THIRD_PARTY_NOTICES.md"
LICENCE_NAMES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "LICENCE", "COPYING")
NOTICE_NAMES = ("NOTICE", "NOTICE.txt", "NOTICE.md")


def first_existing(directory: Path, names):
    for name in names:
        if (directory / name).is_file():
            return directory / name
    return None


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").rstrip() + "\n"


def fail(message: str):
    print(f"generate-notices: {message}", file=sys.stderr)
    sys.exit(1)


def build(checkouts: Path) -> str:
    config = json.loads((ROOT / "Config/third-party.json").read_text(encoding="utf-8"))
    known = config["packages"]
    resolved = {pin["identity"]: pin for pin in json.loads(RESOLVED.read_text(encoding="utf-8"))["pins"]}

    unknown = sorted(set(resolved) - set(known))
    if unknown:
        fail(
            "these packages are resolved but not in Config/third-party.json: " + ", ".join(unknown)
            + ". Decide whether they ship (ADR D-044), then add them."
        )
    gone = sorted(set(known) - set(resolved))
    if gone:
        fail("Config/third-party.json lists packages that are no longer resolved: " + ", ".join(gone))
    if not checkouts.is_dir():
        fail(f"{checkouts} doesn't exist; build once first (task build)")

    entries = []  # (name, version, url, licence, where, text, notice)
    for identity, info in sorted(known.items(), key=lambda item: item[1]["name"].lower()):
        if not info["shipped"]:
            continue
        pin = resolved[identity]
        url = pin["location"].removesuffix(".git")
        version = pin["state"].get("version") or pin["state"]["revision"][:12]
        directory = checkouts / Path(pin["location"]).name.removesuffix(".git")
        licence = first_existing(directory, LICENCE_NAMES)
        if licence is None:
            fail(f"no licence file found for {info['name']} in {directory}")
        text = read(licence)
        notice_file = first_existing(directory, NOTICE_NAMES)
        notice = read(notice_file) if notice_file else None
        where = info["in"] + (f" (through {info['via']})" if "via" in info else "")
        entries.append((info["name"], version, url, info["license"], where, text, notice))
        # Code a package carries inside itself, under its own licence.
        for part in info.get("parts", []):
            part_file = directory / part["path"]
            if not part_file.is_file():
                fail(f"{part['name']}'s licence {part['path']} isn't in {directory}")
            entries.append((
                f"{part['name']} (inside {info['name']})", version, url, part["license"], where, read(part_file), None
            ))
    for item in config["vendored"]:
        licence = ROOT / item["licenseFile"]
        if not licence.is_file():
            fail(f"{item['licenseFile']} is missing; run task vendor:llama")
        version = (ROOT / item["versionFile"]).read_text(encoding="utf-8").strip()
        entries.append((item["name"], version, item["url"], item["license"], item["in"], read(licence), None))
    entries.sort(key=lambda entry: entry[0].lower())

    # A licence text several components share (the Apache-2.0 files come in four slightly different
    # forms) is printed once at the end and referred to by number.
    counts = {}
    for entry in entries:
        counts[entry[5]] = counts.get(entry[5], 0) + 1
    shared = sorted((text for text, n in counts.items() if n > 1), key=lambda t: (-counts[t], t))
    numbers = {text: index + 1 for index, text in enumerate(shared)}

    out = ["# Third-party notices\n"]
    out.append(
        "Quail includes the software below. Each project's licence text, and any notice it asks us to "
        "carry, is reproduced here. This file is generated by `task notices` from `Config/third-party.json`, "
        "`Package.resolved` and the packages' own licence files (ADR D-044); do not edit it by hand.\n"
    )
    out.append("| Component | Version | Licence | Shipped in |\n| --- | --- | --- | --- |")
    for name, version, _url, licence, where, _text, _notice in entries:
        out.append(f"| {name} | {version} | {licence} | {where} |")
    out.append("")
    for name, version, url, licence, _where, text, notice in entries:
        out.append(f"## {name} {version}\n")
        out.append(f"{url}  ")
        out.append(f"Licence: {licence}\n")
        if text in numbers:
            out.append(f"Licence text: number {numbers[text]} at the end of this file.\n")
        else:
            out.append("```text\n" + text.rstrip() + "\n```\n")
        if notice:
            out.append("Notice file:\n\n```text\n" + notice.rstrip() + "\n```\n")
    for text, number in numbers.items():
        users = ", ".join(entry[0] for entry in entries if entry[5] == text)
        out.append(f"## Licence text {number}\n")
        out.append(f"Used by: {users}.\n")
        out.append("```text\n" + text.rstrip() + "\n```\n")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--checkouts", default=str(ROOT / "DerivedData/SourcePackages/checkouts"))
    args = parser.parse_args()
    text = build(Path(args.checkouts))
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != text:
            fail(f"{OUTPUT.relative_to(ROOT)} is out of date; run: task notices, and commit the result")
        print("notices up to date")
        return
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(text) // 1024} KB)")


if __name__ == "__main__":
    main()
